# Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.feature_selection import VarianceThreshold


pd.set_option('display.max_columns', None)



df = pd.read_csv('willenscharen.csv', encoding='latin1', delimiter = ',', index_col = 0)
df = df.backfill(axis=0)
df = df.ffill(axis=0)

df = df.iloc[22:]
df

,bfwls,LDIz,LTPad,LFPad,QPad,WPad,NPad,QSarl,WSarl,QWill,ObereStoer,Buenzau,Aalbek,Willenscharen_pegel_cm,Willenscharen_radar_mm
tstamp,,,,,,,,,,,,,,,
2014-01-02 00:00:00,106,1000.100000,2.600000,90.000000,2.219302,34.0,0.0,3.118159,491.3002,6.912554,0.0,0.0,0.0,179.0,0.0
2014-01-02 01:00:00,106,999.000000,2.500000,90.000000,2.219516,34.0,0.0,3.086809,490.7000,6.796437,0.0,0.0,0.0,178.0,0.0
2014-01-02 02:00:00,106,998.400000,3.300000,89.000000,2.219943,34.0,0.0,3.086918,490.7000,6.679450,0.1,0.0,0.0,177.0,0.0
2014-01-02 03:00:00,106,997.500000,3.800000,87.000000,2.220371,34.0,0.0,3.102725,491.0000,6.679261,0.0,0.0,0.0,177.0,0.0
2014-01-02 04:00:00,106,996.900000,4.100000,87.000000,2.295369,35.0,0.0,3.113299,491.2000,6.679072,0.0,0.0,0.0,177.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-06 02:00:00,100,1024.100000,-0.908333,81.608333,3.754911,62.0,0.0,4.643617,518.0000,9.614127,0.0,0.0,0.0,207.0,0.0
2022-03-06 03:00:00,100,1023.966667,-0.650000,80.083333,3.754911,62.0,0.0,4.643617,518.0000,9.507003,0.0,0.0,0.0,206.0,0.0
2022-03-06 04:00:00,100,1023.983333,0.208333,71.200000,3.675090,61.0,0.0,4.643617,518.0000,9.399932,0.0,0.0,0.0,205.0,0.0
2022-03-06 05:00:00,100,1024.150000,0.358333,68.075000,3.675090,61.0,0.0,4.643617,518.0000,9.399932,0.0,0.0,0.0,205.0,0.0
2022-03-06 06:00:00,100,1024.300000,0.058333,72.525000,3.675090,61.0,0.0,4.588000,517.0000,9.507003,0.0,0.0,0.0,206.0,0.0

# Standardize

In [2]:
df_unstand = df

standardScaler = preprocessing.StandardScaler()
standardizedData = standardScaler.fit_transform(df)

df = pd.DataFrame(standardizedData, columns=df.columns, index=df.index)
df

,bfwls,LDIz,LTPad,LFPad,QPad,WPad,NPad,QSarl,WSarl,QWill,ObereStoer,Buenzau,Aalbek,Willenscharen_pegel_cm,Willenscharen_radar_mm
tstamp,,,,,,,,,,,,,,,
2014-01-02 00:00:00,0.540445,-1.152654,-1.031370,0.455491,0.055854,-0.198930,-0.195832,0.142520,0.279728,0.211747,-0.204285,-0.213547,-0.211022,0.180257,-0.222882
2014-01-02 01:00:00,0.540445,-1.261591,-1.045719,0.455491,0.055991,-0.198930,-0.195832,0.130745,0.265561,0.186939,-0.204285,-0.213547,-0.211022,0.153226,-0.222882
2014-01-02 02:00:00,0.540445,-1.321011,-0.930928,0.389272,0.056263,-0.198930,-0.195832,0.130785,0.265561,0.161944,0.029659,-0.213547,-0.211022,0.126196,-0.222882
2014-01-02 03:00:00,0.540445,-1.410141,-0.859184,0.256832,0.056535,-0.198930,-0.195832,0.136723,0.272642,0.161904,-0.204285,-0.213547,-0.211022,0.126196,-0.222882
2014-01-02 04:00:00,0.540445,-1.469562,-0.816138,0.256832,0.104273,-0.144214,-0.195832,0.140695,0.277363,0.161864,-0.204285,-0.213547,-0.211022,0.126196,-0.222882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-06 02:00:00,0.337437,1.224156,-1.534776,-0.100204,1.033299,1.333107,-0.195832,0.715518,0.909977,0.788939,-0.204285,-0.213547,-0.211022,0.937117,-0.222882
2022-03-06 03:00:00,0.337437,1.210951,-1.497708,-0.201189,1.033299,1.333107,-0.195832,0.715518,0.909977,0.766052,-0.204285,-0.213547,-0.211022,0.910087,-0.222882
2022-03-06 04:00:00,0.337437,1.212602,-1.374547,-0.789442,0.982491,1.278392,-0.195832,0.715518,0.909977,0.743176,-0.204285,-0.213547,-0.211022,0.883056,-0.222882
2022-03-06 05:00:00,0.337437,1.229108,-1.353024,-0.996379,0.982491,1.278392,-0.195832,0.715518,0.909977,0.743176,-0.204285,-0.213547,-0.211022,0.883056,-0.222882
2022-03-06 06:00:00,0.337437,1.243963,-1.396071,-0.701701,0.982491,1.278392,-0.195832,0.694627,0.886372,0.766052,-0.204285,-0.213547,-0.211022,0.910087,-0.222882

# Sampling

### Convert to Array and create the samples as desired

In [3]:
three_d = 15*3*24

df_list = df.values.tolist()
df_list_flat_x = [cell for row in df_list for cell in row]
df_list_flat_y = df_list_flat_x[13::15]

df_x_arr = []
df_y_arr = []



for i in range(70000):
  df_x_arr.append(df_list_flat_x[i*15:i*15 + three_d])
### Convert to Array and create the features as desired

for i in range(70000):
  df_y_arr.append(df_list_flat_y[i + 72:i + 96])

### Convert back to pandas structure

In [4]:
df_x = pd.DataFrame(df_x_arr)
df_y = pd.DataFrame(df_y_arr)

### Restore the naming

In [5]:
df_x_rename = df_x
### Convert back to pandas structure

df_x_rename['date'] = df.iloc[0:70000].index
df_x_rename = df_x_rename.set_index(['date'])
df_x_rename.index = pd.to_datetime(df_x_rename.index)


for i in range(0, 1066, 15):
    df_x_rename = df_x_rename.rename(columns={
        df_x_rename.columns[i + 0]: "bfwls+" + str(i/15),
        df_x_rename.columns[i + 1]: "LDIz+" + str(i/15),
        df_x_rename.columns[i + 2]: "LTPad+" + str(i/15),
        df_x_rename.columns[i + 3]: "LFPad+" + str(i/15),
        df_x_rename.columns[i + 4]: "QPad+" + str(i/15),
        df_x_rename.columns[i + 5]: "WPad+" + str(i/15),
        df_x_rename.columns[i + 6]: "NPad+" + str(i/15),
        df_x_rename.columns[i + 7]: "QSarl+" + str(i/15),
        df_x_rename.columns[i + 8]: "WSarl+" + str(i/15),
        df_x_rename.columns[i + 9]: "QWill+" + str(i/15),
        df_x_rename.columns[i + 10]: "ObereStoer+" + str(i/15),
        df_x_rename.columns[i + 11]: "Buenzau+" + str(i/15),
        df_x_rename.columns[i + 12]: "Aalbek+" + str(i/15),
        df_x_rename.columns[i + 13]: "Willenscharen_pegel_cm+" + str(i/15),
        df_x_rename.columns[i + 14]: "Willenscharen_radar_mm+" + str(i/15)
           })
    
df_x_final = df_x_rename

In [6]:
df_y_rename = df_y

df_y_rename['date'] = df.iloc[0:70000].index
df_y_rename = df_y_rename.set_index(['date'])
df_y_rename.index = pd.to_datetime(df_y_rename.index)


df_y_final = df_y_rename

### Output the samples

In [7]:
df_x_final

,bfwls+0.0,LDIz+0.0,LTPad+0.0,LFPad+0.0,QPad+0.0,WPad+0.0,NPad+0.0,QSarl+0.0,WSarl+0.0,QWill+0.0,ObereStoer+0.0,Buenzau+0.0,Aalbek+0.0,Willenscharen_pegel_cm+0.0,Willenscharen_radar_mm+0.0,bfwls+1.0,LDIz+1.0,LTPad+1.0,LFPad+1.0,QPad+1.0,WPad+1.0,NPad+1.0,QSarl+1.0,WSarl+1.0,QWill+1.0,ObereStoer+1.0,Buenzau+1.0,Aalbek+1.0,Willenscharen_pegel_cm+1.0,Willenscharen_radar_mm+1.0,bfwls+2.0,LDIz+2.0,LTPad+2.0,LFPad+2.0,QPad+2.0,WPad+2.0,NPad+2.0,QSarl+2.0,WSarl+2.0,QWill+2.0,ObereStoer+2.0,Buenzau+2.0,Aalbek+2.0,Willenscharen_pegel_cm+2.0,Willenscharen_radar_mm+2.0,bfwls+3.0,LDIz+3.0,LTPad+3.0,LFPad+3.0,QPad+3.0,WPad+3.0,NPad+3.0,QSarl+3.0,WSarl+3.0,QWill+3.0,ObereStoer+3.0,Buenzau+3.0,Aalbek+3.0,Willenscharen_pegel_cm+3.0,Willenscharen_radar_mm+3.0,bfwls+4.0,LDIz+4.0,LTPad+4.0,LFPad+4.0,QPad+4.0,WPad+4.0,NPad+4.0,QSarl+4.0,WSarl+4.0,QWill+4.0,ObereStoer+4.0,Buenzau+4.0,Aalbek+4.0,Willenscharen_pegel_cm+4.0,Willenscharen_radar_mm+4.0,bfwls+5.0,LDIz+5.0,LTPad+5.0,LFPad+5.0,QPad+5.0,WPad+5.0,NPad+5.0,QSarl+5.0,WSarl+5.0,QWill+5.0,ObereStoer+5.0,Buenzau+5.0,Aalbek+5.0,Willenscharen_pegel_cm+5.0,Willenscharen_radar_mm+5.0,bfwls+6.0,LDIz+6.0,LTPad+6.0,LFPad+6.0,QPad+6.0,WPad+6.0,NPad+6.0,QSarl+6.0,WSarl+6.0,QWill+6.0,ObereStoer+6.0,Buenzau+6.0,Aalbek+6.0,Willenscharen_pegel_cm+6.0,Willenscharen_radar_mm+6.0,bfwls+7.0,LDIz+7.0,LTPad+7.0,LFPad+7.0,QPad+7.0,WPad+7.0,NPad+7.0,QSarl+7.0,WSarl+7.0,QWill+7.0,ObereStoer+7.0,Buenzau+7.0,Aalbek+7.0,Willenscharen_pegel_cm+7.0,Willenscharen_radar_mm+7.0,bfwls+8.0,LDIz+8.0,LTPad+8.0,LFPad+8.0,QPad+8.0,WPad+8.0,NPad+8.0,QSarl+8.0,WSarl+8.0,QWill+8.0,ObereStoer+8.0,Buenzau+8.0,Aalbek+8.0,Willenscharen_pegel_cm+8.0,Willenscharen_radar_mm+8.0,bfwls+9.0,LDIz+9.0,LTPad+9.0,LFPad+9.0,QPad+9.0,WPad+9.0,NPad+9.0,QSarl+9.0,WSarl+9.0,QWill+9.0,ObereStoer+9.0,Buenzau+9.0,Aalbek+9.0,Willenscharen_pegel_cm+9.0,Willenscharen_radar_mm+9.0,bfwls+10.0,LDIz+10.0,LTPad+10.0,LFPad+10.0,QPad+10.0,WPad+10.0,NPad+10.0,QSarl+10.0,WSarl+10.0,QWill+10.0,ObereStoer+10.0,Buenzau+10.0,Aalbek+10.0,Willenscharen_pegel_cm+10.0,Willenscharen_radar_mm+10.0,bfwls+11.0,LDIz+11.0,LTPad+11.0,LFPad+11.0,QPad+11.0,WPad+11.0,NPad+11.0,QSarl+11.0,WSarl+11.0,QWill+11.0,ObereStoer+11.0,Buenzau+11.0,Aalbek+11.0,Willenscharen_pegel_cm+11.0,Willenscharen_radar_mm+11.0,bfwls+12.0,LDIz+12.0,LTPad+12.0,LFPad+12.0,QPad+12.0,WPad+12.0,NPad+12.0,QSarl+12.0,WSarl+12.0,QWill+12.0,ObereStoer+12.0,Buenzau+12.0,Aalbek+12.0,Willenscharen_pegel_cm+12.0,Willenscharen_radar_mm+12.0,bfwls+13.0,LDIz+13.0,LTPad+13.0,LFPad+13.0,QPad+13.0,WPad+13.0,NPad+13.0,QSarl+13.0,WSarl+13.0,QWill+13.0,ObereStoer+13.0,Buenzau+13.0,Aalbek+13.0,Willenscharen_pegel_cm+13.0,Willenscharen_radar_mm+13.0,bfwls+14.0,LDIz+14.0,LTPad+14.0,LFPad+14.0,QPad+14.0,WPad+14.0,NPad+14.0,QSarl+14.0,WSarl+14.0,QWill+14.0,ObereStoer+14.0,Buenzau+14.0,Aalbek+14.0,Willenscharen_pegel_cm+14.0,Willenscharen_radar_mm+14.0,bfwls+15.0,LDIz+15.0,LTPad+15.0,LFPad+15.0,QPad+15.0,WPad+15.0,NPad+15.0,QSarl+15.0,WSarl+15.0,QWill+15.0,ObereStoer+15.0,Buenzau+15.0,Aalbek+15.0,Willenscharen_pegel_cm+15.0,Willenscharen_radar_mm+15.0,bfwls+16.0,LDIz+16.0,LTPad+16.0,LFPad+16.0,QPad+16.0,WPad+16.0,NPad+16.0,QSarl+16.0,WSarl+16.0,QWill+16.0,ObereStoer+16.0,Buenzau+16.0,Aalbek+16.0,Willenscharen_pegel_cm+16.0,Willenscharen_radar_mm+16.0,bfwls+17.0,LDIz+17.0,LTPad+17.0,LFPad+17.0,QPad+17.0,WPad+17.0,NPad+17.0,QSarl+17.0,WSarl+17.0,QWill+17.0,ObereStoer+17.0,Buenzau+17.0,Aalbek+17.0,Willenscharen_pegel_cm+17.0,Willenscharen_radar_mm+17.0,bfwls+18.0,LDIz+18.0,LTPad+18.0,LFPad+18.0,QPad+18.0,WPad+18.0,NPad+18.0,QSarl+18.0,WSarl+18.0,QWill+18.0,ObereStoer+18.0,Buenzau+18.0,Aalbek+18.0,Willenscharen_pegel_cm+18.0,Willenscharen_radar_mm+18.0,bfwls+19.0,LDIz+19.0,LTPad+19.0,LFPad+19.0,QPad+19.0,WPad+19.0,NPad+19.0,QSarl+19.0,WSarl+19.0,QWill+19.0,ObereStoer+19.0,Buenzau+19.0,Aalbek+19.0,Willenscharen_pegel_cm+19.0,Willenscharen_radar_mm+19.0,bfwls+20.0,LDIz+20.0,LTPad+20.0,LFPad+20.0,QPad+20.0,WPad+20.0,NPad+20.0,QSarl+20.0,WSarl+20.0,QWill+20.0,ObereStoer+20.0,Buenzau+20.0,Aalbek+20.0,Willenscharen_pegel_cm+20.0,Willenscharen_radar_mm+20.0,bfwls+21.0,LDIz+21.0,LTPad+21.0,LFPad+21.0,QPad+21.0,WPad+21.0,NPad+21.0,QSarl+21.0,WSarl+21.0,QWill+21.0,ObereStoer+21.0,Buenzau+21.0,Aalbek+21.0,Willenscharen_pegel_cm+21.0,Willenscharen_radar_mm+21.0,bfwls+22.0,LDIz+22.0,LTPad+22.0,LFPad+22.0,QPad+22.0,WPad+22.0,NPad+22.0,QSarl+22.0,WSarl+22.0,QWill+22.0,ObereStoer+22.0,Buenzau+22.0,Aalbek+22.0,Willenscharen_pegel_cm+22.0,Willenscharen_radar_mm+22.0,bfwls+23.0,LDIz+23.0,LTPad+23.0,LFPad+23.0,QPad+23.0,WPad+23.0,NPad+23.0,QSarl+23.0,WSarl+23.0,QWill+23.0,ObereStoer+23.0,Buenzau+23.0,Aalbek+23.0,Willenscharen_pegel_cm+23.0,Willenscharen_radar_mm+23.0,bfwls+24.0,LDIz+24.0,LTPad+24.0,LFPad+24.0,QPad+24.0,WPad+24.0,NPad+24.0,QSarl+24.0,WSarl+24.0,QWill+24.0,ObereStoer+24.0,Buenzau+24.0,Aalbek+24.0,Willenscharen_pegel_cm+24.0,Willenscharen_radar_mm+24.0,bfwls+25.0,LDIz+25.0,LTPad+25.0,LFPad+25.0,QPad+25.0,WPad+25.0,NPad+25.0,QSarl+25.0,WSarl+25.0,QWill+25.0,ObereStoer+25.0,Buenzau+25.0,Aalbek+25.0,Willenscharen_pegel_cm+25.0,Willenscharen_radar_mm+25.0,bfwls+26.0,LDIz+26.0,LTPad+26.0,LFPad+26.0,QPad+26.0,WPad+26.0,NPad+26.0,QSarl+26.0,WSarl+26.0,QWill+26.0,ObereStoer+26.0,Buenzau+26.0,Aalbek+26.0,Willenscharen_pegel_cm+26.0,Willenscharen_radar_mm+26.0,bfwls+27.0,LDIz+27.0,LTPad+27.0,LFPad+27.0,QPad+27.0,WPad+27.0,NPad+27.0,QSarl+27.0,WSarl+27.0,QWill+27.0,ObereStoer+27.0,Buenzau+27.0,Aalbek+27.0,Willenscharen_pegel_cm+27.0,Willenscharen_radar_mm+27.0,bfwls+28.0,LDIz+28.0,LTPad+28.0,LFPad+28.0,QPad+28.0,WPad+28.0,NPad+28.0,QSarl+28.0,WSarl+28.0,QWill+28.0,ObereStoer+28.0,Buenzau+28.0,Aalbek+28.0,Willenscharen_pegel_cm+28.0,Willenscharen_radar_mm+28.0,bfwls+29.0,LDIz+29.0,LTPad+29.0,LFPad+29.0,QPad+29.0,WPad+29.0,NPad+29.0,QSarl+29.0,WSarl+29.0,QWill+29.0,ObereStoer+29.0,Buenzau+29.0,Aalbek+29.0,Willenscharen_pegel_cm+29.0,Willenscharen_radar_mm+29.0,bfwls+30.0,LDIz+30.0,LTPad+30.0,LFPad+30.0,QPad+30.0,WPad+30.0,NPad+30.0,QSarl+30.0,WSarl+30.0,QWill+30.0,ObereStoer+30.0,Buenzau+30.0,Aalbek+30.0,Willenscharen_pegel_cm+30.0,Willenscharen_radar_mm+30.0,bfwls+31.0,LDIz+31.0,LTPad+31.0,LFPad+31.0,QPad+31.0,WPad+31.0,NPad+31.0,QSarl+31.0,WSarl+31.0,QWill+31.0,ObereStoer+31.0,Buenzau+31.0,Aalbek+31.0,Willenscharen_pegel_cm+31.0,Willenscharen_radar_mm+31.0,bfwls+32.0,LDIz+32.0,LTPad+32.0,LFPad+32.0,QPad+32.0,WPad+32.0,NPad+32.0,QSarl+32.0,WSarl+32.0,QWill+32.0,ObereStoer+32.0,Buenzau+32.0,Aalbek+32.0,Willenscharen_pegel_cm+32.0,Willenscharen_radar_mm+32.0,bfwls+33.0,LDIz+33.0,LTPad+33.0,LFPad+33.0,QPad+33.0,WPad+33.0,NPad+33.0,QSarl+33.0,WSarl+33.0,QWill+33.0,ObereStoer+33.0,Buenzau+33.0,Aalbek+33.0,Willenscharen_pegel_cm+33.0,Willenscharen_radar_mm+33.0,bfwls+34.0,LDIz+34.0,LTPad+34.0,LFPad+34.0,QPad+34.0,WPad+34.0,NPad+34.0,QSarl+34.0,WSarl+34.0,QWill+34.0,ObereStoer+34.0,Buenzau+34.0,Aalbek+34.0,Willenscharen_pegel_cm+34.0,Willenscharen_radar_mm+34.0,bfwls+35.0,LDIz+35.0,LTPad+35.0,LFPad+35.0,QPad+35.0,WPad+35.0,NPad+35.0,QSarl+35.0,WSarl+35.0,QWill+35.0,ObereStoer+35.0,Buenzau+35.0,Aalbek+35.0,Willenscharen_pegel_cm+35.0,Willenscharen_radar_mm+35.0,bfwls+36.0,LDIz+36.0,LTPad+36.0,LFPad+36.0,QPad+36.0,WPad+36.0,NPad+36.0,QSarl+36.0,WSarl+36.0,QWill+36.0,ObereStoer+36.0,Buenzau+36.0,Aalbek+36.0,Willenscharen_pegel_cm+36.0,Willenscharen_radar_mm+36.0,bfwls+37.0,LDIz+37.0,LTPad+37.0,LFPad+37.0,QPad+37.0,WPad+37.0,NPad+37.0,QSarl+37.0,WSarl+37.0,QWill+37.0,ObereStoer+37.0,Buenzau+37.0,Aalbek+37.0,Willenscharen_pegel_cm+37.0,Willenscharen_radar_mm+37.0,bfwls+38.0,LDIz+38.0,LTPad+38.0,LFPad+38.0,QPad+38.0,WPad+38.0,NPad+38.0,QSarl+38.0,WSarl+38.0,QWill+38.0,ObereStoer+38.0,Buenzau+38.0,Aalbek+38.0,Willenscharen_pegel_cm+38.0,Willenscharen_radar_mm+38.0,bfwls+39.0,LDIz+39.0,LTPad+39.0,LFPad+39.0,QPad+39.0,WPad+39.0,NPad+39.0,QSarl+39.0,WSarl+39.0,QWill+39.0,ObereStoer+39.0,Buenzau+39.0,Aalbek+39.0,Willenscharen_pegel_cm+39.0,Willenscharen_radar_mm+39.0,bfwls+40.0,LDIz+40.0,LTPad+40.0,LFPad+40.0,QPad+40.0,WPad+40.0,NPad+40.0,QSarl+40.0,WSarl+40.0,QWill+40.0,ObereStoer+40.0,Buenzau+40.0,Aalbek+40.0,Willenscharen_pegel_cm+40.0,Willenscharen_radar_mm+40.0,bfwls+41.0,LDIz+41.0,LTPad+41.0,LFPad+41.0,QPad+41.0,WPad+41.0,NPad+41.0,QSarl+41.0,WSarl+41.0,QWill+41.0,ObereStoer+41.0,Buenzau+41.0,Aalbek+41.0,Willenscharen_pegel_cm+41.0,Willenscharen_radar_mm+41.0,bfwls+42.0,LDIz+42.0,LTPad+42.0,LFPad+42.0,QPad+42.0,WPad+42.0,NPad+42.0,QSarl+42.0,WSarl+42.0,QWill+42.0,ObereStoer+42.0,Buenzau+42.0,Aalbek+42.0,Willenscharen_pegel_cm+42.0,Willenscharen_radar_mm+42.0,bfwls+43.0,LDIz+43.0,LTPad+43.0,LFPad+43.0,QPad+43.0,WPad+43.0,NPad+43.0,QSarl+43.0,WSarl+43.0,QWill+43.0,ObereStoer+43.0,Buenzau+43.0,Aalbek+43.0,Willenscharen_pegel_cm+43.0,Willenscharen_radar_mm+43.0,bfwls+44.0,LDIz+44.0,LTPad+44.0,LFPad+44.0,QPad+44.0,WPad+44.0,NPad+44.0,QSarl+44.0,WSarl+44.0,QWill+44.0,ObereStoer+44.0,Buenzau+44.0,Aalbek+44.0,Willenscharen_pegel_cm+44.0,Willenscharen_radar_mm+44.0,bfwls+45.0,LDIz+45.0,LTPad+45.0,LFPad+45.0,QPad+45.0,WPad+45.0,NPad+45.0,QSarl+45.0,WSarl+45.0,QWill+45.0,ObereStoer+45.0,Buenzau+45.0,Aalbek+45.0,Willenscharen_pegel_cm+45.0,Willenscharen_radar_mm+45.0,bfwls+46.0,LDIz+46.0,LTPad+46.0,LFPad+46.0,QPad+46.0,WPad+46.0,NPad+46.0,QSarl+46.0,WSarl+46.0,QWill+46.0,ObereStoer+46.0,Buenzau+46.0,Aalbek+46.0,Willenscharen_pegel_cm+46.0,Willenscharen_radar_mm+46.0,bfwls+47.0,LDIz+47.0,LTPad+47.0,LFPad+47.0,QPad+47.0,WPad+47.0,NPad+47.0,QSarl+47.0,WSarl+47.0,QWill+47.0,ObereStoer+47.0,Buenzau+47.0,Aalbek+47.0,Willenscharen_pegel_cm+47.0,Willenscharen_radar_mm+47.0,bfwls+48.0,LDIz+48.0,LTPad+48.0,LFPad+48.0,QPad+48.0,WPad+48.0,NPad+48.0,QSarl+48.0,WSarl+48.0,QWill+48.0,ObereStoer+48.0,Buenzau+48.0,Aalbek+48.0,Willenscharen_pegel_cm+48.0,Willenscharen_radar_mm+48.0,bfwls+49.0,LDIz+49.0,LTPad+49.0,LFPad+49.0,QPad+49.0,WPad+49.0,NPad+49.0,QSarl+49.0,WSarl+49.0,QWill+49.0,ObereStoer+49.0,Buenzau+49.0,Aalbek+49.0,Willenscharen_pegel_cm+49.0,Willenscharen_radar_mm+49.0,bfwls+50.0,LDIz+50.0,LTPad+50.0,LFPad+50.0,QPad+50.0,WPad+50.0,NPad+50.0,QSarl+50.0,WSarl+50.0,QWill+50.0,ObereStoer+50.0,Buenzau+50.0,Aalbek+50.0,Willenscharen_pegel_cm+50.0,Willenscharen_radar_mm+50.0,bfwls+51.0,LDIz+51.0,LTPad+51.0,LFPad+51.0,QPad+51.0,WPad+51.0,NPad+51.0,QSarl+51.0,WSarl+51.0,QWill+51.0,ObereStoer+51.0,Buenzau+51.0,Aalbek+51.0,Willenscharen_pegel_cm+51.0,Willenscharen_radar_mm+51.0,bfwls+52.0,LDIz+52.0,LTPad+52.0,LFPad+52.0,QPad+52.0,WPad+52.0,NPad+52.0,QSarl+52.0,WSarl+52.0,QWill+52.0,ObereStoer+52.0,Buenzau+52.0,Aalbek+52.0,Willenscharen_pegel_cm+52.0,Willenscharen_radar_mm+52.0,bfwls+53.0,LDIz+53.0,LTPad+53.0,LFPad+53.0,QPad+53.0,WPad+53.0,NPad+53.0,QSarl+53.0,WSarl+53.0,QWill+53.0,ObereStoer+53.0,Buenzau+53.0,Aalbek+53.0,Willenscharen_pegel_cm+53.0,Willenscharen_radar_mm+53.0,bfwls+54.0,LDIz+54.0,LTPad+54.0,LFPad+54.0,QPad+54.0,WPad+54.0,NPad+54.0,QSarl+54.0,WSarl+54.0,QWill+54.0,ObereStoer+54.0,Buenzau+54.0,Aalbek+54.0,Willenscharen_pegel_cm+54.0,Willenscharen_radar_mm+54.0,bfwls+55.0,LDIz+55.0,LTPad+55.0,LFPad+55.0,QPad+55.0,WPad+55.0,NPad+55.0,QSarl+55.0,WSarl+55.0,QWill+55.0,ObereStoer+55.0,Buenzau+55.0,Aalbek+55.0,Willenscharen_pegel_cm+55.0,Willenscharen_radar_mm+55.0,bfwls+56.0,LDIz+56.0,LTPad+56.0,LFPad+56.0,QPad+56.0,WPad+56.0,NPad+56.0,QSarl+56.0,WSarl+56.0,QWill+56.0,ObereStoer+56.0,Buenzau+56.0,Aalbek+56.0,Willenscharen_pegel_cm+56.0,Willenscharen_radar_mm+56.0,bfwls+57.0,LDIz+57.0,LTPad+57.0,LFPad+57.0,QPad+57.0,WPad+57.0,NPad+57.0,QSarl+57.0,WSarl+57.0,QWill+57.0,ObereStoer+57.0,Buenzau+57.0,Aalbek+57.0,Willenscharen_pegel_cm+57.0,Willenscharen_radar_mm+57.0,bfwls+58.0,LDIz+58.0,LTPad+58.0,LFPad+58.0,QPad+58.0,WPad+58.0,NPad+58.0,QSarl+58.0,WSarl+58.0,QWill+58.0,ObereStoer+58.0,Buenzau+58.0,Aalbek+58.0,Willenscharen_pegel_cm+58.0,Willenscharen_radar_mm+58.0,bfwls+59.0,LDIz+59.0,LTPad+59.0,LFPad+59.0,QPad+59.0,WPad+59.0,NPad+59.0,QSarl+59.0,WSarl+59.0,QWill+59.0,ObereStoer+59.0,Buenzau+59.0,Aalbek+59.0,Willenscharen_pegel_cm+59.0,Willenscharen_radar_mm+59.0,bfwls+60.0,LDIz+60.0,LTPad+60.0,LFPad+60.0,QPad+60.0,WPad+60.0,NPad+60.0,QSarl+60.0,WSarl+60.0,QWill+60.0,ObereStoer+60.0,Buenzau+60.0,Aalbek+60.0,Willenscharen_pegel_cm+60.0,Willenscharen_radar_mm+60.0,bfwls+61.0,LDIz+61.0,LTPad+61.0,LFPad+61.0,QPad+61.0,WPad+61.0,NPad+61.0,QSarl+61.0,WSarl+61.0,QWill+61.0,ObereStoer+61.0,Buenzau+61.0,Aalbek+61.0,Willenscharen_pegel_cm+61.0,Willenscharen_radar_mm+61.0,bfwls+62.0,LDIz+62.0,LTPad+62.0,LFPad+62.0,QPad+62.0,WPad+62.0,NPad+62.0,QSarl+62.0,WSarl+62.0,QWill+62.0,ObereStoer+62.0,Buenzau+62.0,Aalbek+62.0,Willenscharen_pegel_cm+62.0,Willenscharen_radar_mm+62.0,bfwls+63.0,LDIz+63.0,LTPad+63.0,LFPad+63.0,QPad+63.0,WPad+63.0,NPad+63.0,QSarl+63.0,WSarl+63.0,QWill+63.0,ObereStoer+63.0,Buenzau+63.0,Aalbek+63.0,Willenscharen_pegel_cm+63.0,Willenscharen_radar_mm+63.0,bfwls+64.0,LDIz+64.0,LTPad+64.0,LFPad+64.0,QPad+64.0,WPad+64.0,NPad+64.0,QSarl+64.0,WSarl+64.0,QWill+64.0,ObereStoer+64.0,Buenzau+64.0,Aalbek+64.0,Willenscharen_pegel_cm+64.0,Willenscharen_radar_mm+64.0,bfwls+65.0,LDIz+65.0,LTPad+65.0,LFPad+65.0,QPad+65.0,WPad+65.0,NPad+65.0,QSarl+65.0,WSarl+65.0,QWill+65.0,ObereStoer+65.0,Buenzau+65.0,Aalbek+65.0,Willenscharen_pegel_cm+65.0,Willenscharen_radar_mm+65.0,bfwls+66.0,LDIz+66.0,LTPad+66.0,LFPad+66.0,QPad+66.0,WPad+66.0,NPad+66.0,QSarl+66.0,WSarl+66.0,QWill+66.0,ObereStoer+66.0,Buenzau+66.0,Aalbek+66.0,Willenscharen_pegel_cm+66.0,Willenscharen_radar_mm+66.0,bfwls+67.0,LDIz+67.0,LTPad+67.0,LFPad+67.0,QPad+67.0,WPad+67.0,NPad+67.0,QSarl+67.0,WSarl+67.0,QWill+67.0,ObereStoer+67.0,Buenzau+67.0,Aalbek+67.0,Willenscharen_pegel_cm+67.0,Willenscharen_radar_mm+67.0,bfwls+68.0,LDIz+68.0,LTPad+68.0,LFPad+68.0,QPad+68.0,WPad+68.0,NPad+68.0,QSarl+68.0,WSarl+68.0,QWill+68.0,ObereStoer+68.0,Buenzau+68.0,Aalbek+68.0,Willenscharen_pegel_cm+68.0,Willenscharen_radar_mm+68.0,bfwls+69.0,LDIz+69.0,LTPad+69.0,LFPad+69.0,QPad+69.0,WPad+69.0,NPad+69.0,QSarl+69.0,WSarl+69.0,QWill+69.0,ObereStoer+69.0,Buenzau+69.0,Aalbek+69.0,Willenscharen_pegel_cm+69.0,Willenscharen_radar_mm+69.0,bfwls+70.0,LDIz+70.0,LTPad+70.0,LFPad+70.0,QPad+70.0,WPad+70.0,NPad+70.0,QSarl+70.0,WSarl+70.0,QWill+70.0,ObereStoer+70.0,Buenzau+70.0,Aalbek+70.0,Willenscharen_pegel_cm+70.0,Willenscharen_radar_mm+70.0,bfwls+71.0,LDIz+71.0,LTPad+71.0,LFPad+71.0,QPad+71.0,WPad+71.0,NPad+71.0,QSarl+71.0,WSarl+71.0,QWill+71.0,ObereStoer+71.0,Buenzau+71.0,Aalbek+71.0,Willenscharen_pegel_cm+71.0,Willenscharen_radar_mm+71.0
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [8]:
df_y_final

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
date,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-02 00:00:00,0.315411,0.315411,0.315411,0.315411,0.288380,0.288380,0.288380,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.234318,0.234318,0.234318,0.234318,0.234318,0.234318,0.207288,0.207288
2014-01-02 01:00:00,0.315411,0.315411,0.315411,0.288380,0.288380,0.288380,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.234318,0.234318,0.234318,0.234318,0.234318,0.234318,0.207288,0.207288,0.207288
2014-01-02 02:00:00,0.315411,0.315411,0.288380,0.288380,0.288380,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.234318,0.234318,0.234318,0.234318,0.234318,0.234318,0.207288,0.207288,0.207288,0.207288
2014-01-02 03:00:00,0.315411,0.288380,0.288380,0.288380,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.234318,0.234318,0.234318,0.234318,0.234318,0.234318,0.207288,0.207288,0.207288,0.207288,0.207288
2014-01-02 04:00:00,0.288380,0.288380,0.288380,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.261349,0.234318,0.234318,0.234318,0.234318,0.234318,0.234318,0.207288,0.207288,0.207288,0.207288,0.207288,0.207288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-30 20:00:00,2.694114,2.775206,2.829268,2.856298,2.910360,2.937391,2.964421,2.991452,3.018483,3.045513,3.072544,3.072544,3.099575,3.126606,3.153636,3.180667,3.207698,3.234728,3.234728,3.288790,3.288790,3.288790,3.288790,3.315821
2021-12-30 21:00:00,2.775206,2.829268,2.856298,2.910360,2.937391,2.964421,2.991452,3.018483,3.045513,3.072544,3.072544,3.099575,3.126606,3.153636,3.180667,3.207698,3.234728,3.234728,3.288790,3.288790,3.288790,3.288790,3.315821,3.315821
2021-12-30 22:00:00,2.829268,2.856298,2.910360,2.937391,2.964421,2.991452,3.018483,3.045513,3.072544,3.072544,3.099575,3.126606,3.153636,3.180667,3.207698,3.234728,3.234728,3.288790,3.288790,3.288790,3.288790,3.315821,3.315821,3.315821
2021-12-30 23:00:00,2.856298,2.910360,2.937391,2.964421,2.991452,3.018483,3.045513,3.072544,3.072544,3.099575,3.126606,3.153636,3.180667,3.207698,3.234728,3.234728,3.288790,3.288790,3.288790,3.288790,3.315821,3.315821,3.315821,3.288790
2021-12-31 00:00:00,2.910360,2.937391,2.964421,2.991452,3.018483,3.045513,3.072544,3.072544,3.099575,3.126606,3.153636,3.180667,3.207698,3.234728,3.234728,3.288790,3.288790,3.288790,3.288790,3.315821,3.315821,3.315821,3.288790,3.315821

# PCA

### Creating a PCA with 78 components (so the explained variance is greater then 90%)
### Explained Variance with 2 Components is only ~40%!

In [ ]:
from sklearn.decomposition import PCA as sklearnPCA
pca = sklearnPCA(n_components=78)

model = pca.fit(df_x_final)
pcaTransformedData = model.transform(df_x_final)

### Explained Variance of each Component and Sum

In [ ]:
pca.explained_variance_ratio_

In [ ]:
pca.explained_variance_ratio_.sum()

### Create pandas showing the impact of the features of the first two components and plot some of them

In [ ]:
feature_names = list(df_x_final)
feature_names[0] = list(df_x_final)
feature_names[1] = [abs(ele) for ele in pca.components_[0].tolist()]
feature_names[2] = [abs(ele) for ele in pca.components_[1].tolist()]



df_features = pd.DataFrame(feature_names)
df_features = df_features.iloc[0:3].T

df_features = df_features.set_index([df_features.columns[0]])

matplotlib.rc('figure', figsize=(20, 5), dpi=300)
plt.xticks(rotation=90)

i = 1
plt.plot(df_features[df_features.columns[0]].iloc[i*15:i*15 + 15])
plt.show()

df_features.dtypes
df_features.to_csv('pca_feature.csv')

### Features with high impact on Component 1 are: Abfluss/Wasserstand aller Stationen
### Features with some impact on Component 1 are: Bodenfeuchte, Luftdruck, Lufttemperatur, Luftfeuchte
### Features with low impact on Component 1 are: Niederschlag generell

### Plot first 20000 values for Component 1 and 2 and compare with our Sample Target Y

In [ ]:
#pcaTransformedFrame = pd.DataFrame(pcaTransformedData, columns=["PCA1", "PCA2"])
#pcaTransformedFrame.iloc[0:20000].plot()

pcaTransformedFrame = pd.DataFrame(pcaTransformedData[: , :2], columns=["PCA1", "PCA2"])
pcaTransformedFrame.iloc[0:20000].plot()

In [ ]:
plt.xticks(rotation=90)
plt.plot(df_y_final.iloc[0:20000][df_y_final.columns[0]])
plt.show()

# Feature Selection with Correllation Matrix

### Add Y to to X and calculate Correlation Matrix to filter out irrelevant Features

In [ ]:
df_xy = df_x_final.join(df_y_final)
df_corr_y = df_xy.corr()[:-24]
df_corr_y

### Show average correlation of each feature with Y

In [ ]:
average_corr_y = df_corr_y.iloc[:,1080:1104].mean(axis=1)
average_corr_y

### Filter Features with average correlation of less then 0.2 (not very relevant)

In [ ]:
average_corr_y_filtered = average_corr_y[average_corr_y.abs() < 0.2].dropna()
average_corr_y_filtered

In [ ]:
df_x_drop_irr = df_x_final.drop(df_x_final[average_corr_y_filtered.index], axis=1)
df_x_drop_irr

### Create Correlation Matrix for remaining features to filter out redundant ones

In [ ]:
df_corr = df_x_drop_irr.corr()

In [ ]:
df_corr

### Extract Features with correlation greater then 0.8 to each other (redundant)

In [ ]:
highly_correlated = set()

for i in range(len(df_corr.columns)):### Create Correlation Matrix (which shows correlation between each feature)
    for j in range(i):
        if abs(df_corr.iloc[i, j]) > 0.8:
            col = df_corr.columns[i]
            highly_correlated.add(col)
        
highly_correlated

### Drop one each of those Features

In [ ]:
df_features = df_x_drop_irr.drop(df_corr[highly_correlated], axis=1)

In [ ]:
df_features

In [ ]:
df_features.join(df_y_final).corr()[:-24]